services:
  - type: web
    name: bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8046018994:AAFtjQnXG-h6SXe2Fyxu_rHpus4SsSjIdiI # Replace with your actual bot token
       # Add other necessary environment variables
    plan: free  # Adjust your plan based on your needs

  - type: web
    name: keep-alive-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python keep_alive.py
    envVars:
      - key: BOT_TOKEN
        value: 8046018994:AAFtjQnXG-h6SXe2Fyxu_rHpus4SsSjIdiI  # Reuse or specify new token for keep-alive service if needed
    plan: free  # Adjust your plan

  # Optional: Add another service for `main.py` if it's a separate service
  - type: web
    name: main-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8046018994:AAFtjQnXG-h6SXe2Fyxu_rHpus4SsSjIdiI  # Replace with your actual bot token
    plan: free  # Adjust your plan
